package com.example.kanakku.data.database.dao

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.example.kanakku.data.database.KanakkuDatabase
import com.example.kanakku.data.database.entity.CustomCategoryEntity
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Instrumented tests for CustomCategoryDao.
 *
 * Tests cover:
 * - CRUD operations (insert, update, delete)
 * - Query operations with subcategories
 * - Cascade delete behavior for hierarchical categories
 * - Flow and snapshot query variants
 * - Search and filtering
 * - System vs custom categories
 * - Edge cases and error scenarios
 */
@RunWith(AndroidJUnit4::class)
class CustomCategoryDaoTest {

    private lateinit var database: KanakkuDatabase
    private lateinit var categoryDao: CustomCategoryDao

    @Before
    fun setup() {
        // Create in-memory database for testing
        database = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            KanakkuDatabase::class.java
        )
            .allowMainThreadQueries() // For testing only
            .build()

        categoryDao = database.customCategoryDao()
    }

    @After
    fun teardown() {
        database.close()
    }

    // ==================== Helper Functions ====================

    private fun createTestCategory(
        id: Long = 0,
        name: String = "Test Category",
        icon: String = "🏷️",
        colorHex: String = "#FF0000",
        keywords: String = "test,sample",
        parentId: Long? = null,
        isSystemCategory: Boolean = false,
        sortOrder: Int = 0,
        createdAt: Long = System.currentTimeMillis(),
        updatedAt: Long = System.currentTimeMillis()
    ): CustomCategoryEntity {
        return CustomCategoryEntity(
            id = id,
            name = name,
            icon = icon,
            colorHex = colorHex,
            keywords = keywords,
            parentId = parentId,
            isSystemCategory = isSystemCategory,
            sortOrder = sortOrder,
            createdAt = createdAt,
            updatedAt = updatedAt
        )
    }

    // ==================== Insert Tests ====================

    @Test
    fun insert_singleCategory_returnsRowId() = runTest {
        // Given
        val category = createTestCategory(name = "Food")

        // When
        val rowId = categoryDao.insert(category)

        // Then
        assertTrue(rowId > 0)
        val loaded = categoryDao.getCategoryById(rowId)
        assertNotNull(loaded)
        assertEquals("Food", loaded?.name)
    }

    @Test
    fun insert_withAutoGeneratedId_generatesId() = runTest {
        // Given
        val category = createTestCategory(id = 0, name = "Transport")

        // When
        val rowId = categoryDao.insert(category)

        // Then
        assertTrue(rowId > 0)
        val loaded = categoryDao.getCategoryById(rowId)
        assertEquals("Transport", loaded?.name)
    }

    @Test
    fun insertAll_multipleCategories_returnsAllRowIds() = runTest {
        // Given
        val categories = listOf(
            createTestCategory(name = "Food"),
            createTestCategory(name = "Transport"),
            createTestCategory(name = "Shopping")
        )

        // When
        val rowIds = categoryDao.insertAll(categories)

        // Then
        assertEquals(3, rowIds.size)
        assertTrue(rowIds.all { it > 0 })
    }

    @Test
    fun insert_duplicate_replacesExisting() = runTest {
        // Given
        val category1 = createTestCategory(name = "Food", colorHex = "#FF0000")
        val rowId = categoryDao.insert(category1)

        // When - Insert with same ID but different data
        val category2 = createTestCategory(id = rowId, name = "Food Updated", colorHex = "#00FF00")
        val newRowId = categoryDao.insert(category2)

        // Then
        assertEquals(rowId, newRowId) // Same ID
        val loaded = categoryDao.getCategoryById(rowId)
        assertEquals("Food Updated", loaded?.name)
        assertEquals("#00FF00", loaded?.colorHex)
    }

    @Test
    fun insertAll_withEmptyList_succeeds() = runTest {
        // Given
        val emptyList = emptyList<CustomCategoryEntity>()

        // When
        val rowIds = categoryDao.insertAll(emptyList)

        // Then
        assertTrue(rowIds.isEmpty())
    }

    // ==================== Update Tests ====================

    @Test
    fun update_existingCategory_returnsOne() = runTest {
        // Given
        val category = createTestCategory(name = "Food")
        val rowId = categoryDao.insert(category)

        // When
        val updatedCategory = category.copy(id = rowId, name = "Food & Beverages")
        val updateCount = categoryDao.update(updatedCategory)

        // Then
        assertEquals(1, updateCount)
        val loaded = categoryDao.getCategoryById(rowId)
        assertEquals("Food & Beverages", loaded?.name)
    }

    @Test
    fun update_nonExistentCategory_returnsZero() = runTest {
        // Given
        val category = createTestCategory(id = 999, name = "Non-existent")

        // When
        val updateCount = categoryDao.update(category)

        // Then
        assertEquals(0, updateCount)
    }

    @Test
    fun update_multipleFields_updatesAll() = runTest {
        // Given
        val original = createTestCategory(
            name = "Original",
            icon = "📦",
            colorHex = "#FF0000",
            keywords = "old,keywords",
            sortOrder = 0
        )
        val rowId = categoryDao.insert(original)

        // When
        val updated = original.copy(
            id = rowId,
            name = "Updated",
            icon = "✨",
            colorHex = "#00FF00",
            keywords = "new,updated,keywords",
            sortOrder = 5,
            updatedAt = System.currentTimeMillis()
        )
        categoryDao.update(updated)

        // Then
        val loaded = categoryDao.getCategoryById(rowId)
        assertEquals("Updated", loaded?.name)
        assertEquals("✨", loaded?.icon)
        assertEquals("#00FF00", loaded?.colorHex)
        assertEquals("new,updated,keywords", loaded?.keywords)
        assertEquals(5, loaded?.sortOrder)
    }

    // ==================== Delete Tests ====================

    @Test
    fun delete_existingCategory_returnsOne() = runTest {
        // Given
        val category = createTestCategory(name = "Food")
        val rowId = categoryDao.insert(category)

        // When
        val deleteCount = categoryDao.delete(category.copy(id = rowId))

        // Then
        assertEquals(1, deleteCount)
        assertNull(categoryDao.getCategoryById(rowId))
    }

    @Test
    fun deleteById_existingCategory_returnsOne() = runTest {
        // Given
        val category = createTestCategory(name = "Transport")
        val rowId = categoryDao.insert(category)

        // When
        val deleteCount = categoryDao.deleteById(rowId)

        // Then
        assertEquals(1, deleteCount)
        assertNull(categoryDao.getCategoryById(rowId))
        assertFalse(categoryDao.exists(rowId))
    }

    @Test
    fun deleteById_nonExistentCategory_returnsZero() = runTest {
        // When
        val deleteCount = categoryDao.deleteById(999)

        // Then
        assertEquals(0, deleteCount)
    }

    @Test
    fun deleteAll_removesAllCategories() = runTest {
        // Given
        val categories = listOf(
            createTestCategory(name = "Food"),
            createTestCategory(name = "Transport"),
            createTestCategory(name = "Shopping")
        )
        categoryDao.insertAll(categories)

        // When
        val deleteCount = categoryDao.deleteAll()

        // Then
        assertEquals(3, deleteCount)
        assertEquals(0, categoryDao.getCategoryCount())
    }

    @Test
    fun deleteAllCustomCategories_preservesSystemCategories() = runTest {
        // Given
        val categories = listOf(
            createTestCategory(name = "System Food", isSystemCategory = true),
            createTestCategory(name = "Custom Transport", isSystemCategory = false),
            createTestCategory(name = "Custom Shopping", isSystemCategory = false)
        )
        categoryDao.insertAll(categories)

        // When
        val deleteCount = categoryDao.deleteAllCustomCategories()

        // Then
        assertEquals(2, deleteCount) // Only custom categories deleted
        assertEquals(1, categoryDao.getCategoryCount()) // System category remains
        val remaining = categoryDao.getAllCategoriesSnapshot()
        assertEquals(1, remaining.size)
        assertTrue(remaining[0].isSystemCategory)
    }

    // ==================== Cascade Delete Tests ====================

    @Test
    fun cascadeDelete_deletingParent_deletesSubcategories() = runTest {
        // Given - Parent category with subcategories
        val parentId = categoryDao.insert(createTestCategory(name = "Food"))
        val subcategory1Id = categoryDao.insert(createTestCategory(name = "Restaurants", parentId = parentId))
        val subcategory2Id = categoryDao.insert(createTestCategory(name = "Groceries", parentId = parentId))

        // Verify setup
        assertEquals(3, categoryDao.getCategoryCount())
        assertEquals(2, categoryDao.getSubcategoryCount(parentId))

        // When - Delete parent
        val deleteCount = categoryDao.deleteById(parentId)

        // Then - All subcategories should also be deleted (CASCADE)
        assertEquals(1, deleteCount) // Only counts the parent
        assertEquals(0, categoryDao.getCategoryCount()) // All deleted
        assertNull(categoryDao.getCategoryById(subcategory1Id))
        assertNull(categoryDao.getCategoryById(subcategory2Id))
    }

    @Test
    fun cascadeDelete_multiLevelHierarchy_deletesAllLevels() = runTest {
        // Given - Multi-level hierarchy: Food > Restaurants > Fast Food
        val foodId = categoryDao.insert(createTestCategory(name = "Food"))
        val restaurantsId = categoryDao.insert(createTestCategory(name = "Restaurants", parentId = foodId))
        val fastFoodId = categoryDao.insert(createTestCategory(name = "Fast Food", parentId = restaurantsId))

        // Verify setup
        assertEquals(3, categoryDao.getCategoryCount())

        // When - Delete top-level parent
        categoryDao.deleteById(foodId)

        // Then - All levels should be deleted
        assertEquals(0, categoryDao.getCategoryCount())
        assertNull(categoryDao.getCategoryById(foodId))
        assertNull(categoryDao.getCategoryById(restaurantsId))
        assertNull(categoryDao.getCategoryById(fastFoodId))
    }

    @Test
    fun cascadeDelete_deletingSubcategory_doesNotAffectParent() = runTest {
        // Given
        val parentId = categoryDao.insert(createTestCategory(name = "Food"))
        val subcategoryId = categoryDao.insert(createTestCategory(name = "Restaurants", parentId = parentId))

        // When - Delete subcategory
        categoryDao.deleteById(subcategoryId)

        // Then - Parent should remain
        assertEquals(1, categoryDao.getCategoryCount())
        assertNotNull(categoryDao.getCategoryById(parentId))
        assertNull(categoryDao.getCategoryById(subcategoryId))
    }

    // ==================== Query Tests ====================

    @Test
    fun getAllCategories_returnsAllSortedByOrderAndName() = runTest {
        // Given
        categoryDao.insertAll(
            listOf(
                createTestCategory(name = "Zulu", sortOrder = 2),
                createTestCategory(name = "Alpha", sortOrder = 1),
                createTestCategory(name = "Bravo", sortOrder = 1)
            )
        )

        // When
        val categories = categoryDao.getAllCategories().first()

        // Then
        assertEquals(3, categories.size)
        assertEquals("Alpha", categories[0].name) // sortOrder 1, alphabetically first
        assertEquals("Bravo", categories[1].name) // sortOrder 1, alphabetically second
        assertEquals("Zulu", categories[2].name) // sortOrder 2
    }

    @Test
    fun getAllCategoriesSnapshot_returnsOneTimeSnapshot() = runTest {
        // Given
        categoryDao.insertAll(
            listOf(
                createTestCategory(name = "Food"),
                createTestCategory(name = "Transport")
            )
        )

        // When
        val categories = categoryDao.getAllCategoriesSnapshot()

        // Then
        assertEquals(2, categories.size)
    }

    @Test
    fun getCategoryById_existingCategory_returnsCategory() = runTest {
        // Given
        val category = createTestCategory(name = "Shopping")
        val rowId = categoryDao.insert(category)

        // When
        val loaded = categoryDao.getCategoryById(rowId)

        // Then
        assertNotNull(loaded)
        assertEquals("Shopping", loaded?.name)
    }

    @Test
    fun getCategoryById_nonExistentCategory_returnsNull() = runTest {
        // When
        val loaded = categoryDao.getCategoryById(999)

        // Then
        assertNull(loaded)
    }

    @Test
    fun getCategoryByIdFlow_existingCategory_returnsFlow() = runTest {
        // Given
        val category = createTestCategory(name = "Entertainment")
        val rowId = categoryDao.insert(category)

        // When
        val flow = categoryDao.getCategoryByIdFlow(rowId)
        val loaded = flow.first()

        // Then
        assertNotNull(loaded)
        assertEquals("Entertainment", loaded?.name)
    }

    @Test
    fun getCategoryByIdFlow_nonExistentCategory_returnsNull() = runTest {
        // When
        val flow = categoryDao.getCategoryByIdFlow(999)
        val loaded = flow.first()

        // Then
        assertNull(loaded)
    }

    // ==================== Hierarchical Query Tests ====================

    @Test
    fun getRootCategories_returnsOnlyCategoriesWithoutParent() = runTest {
        // Given
        val parentId = categoryDao.insert(createTestCategory(name = "Food"))
        categoryDao.insert(createTestCategory(name = "Restaurants", parentId = parentId))
        categoryDao.insert(createTestCategory(name = "Transport")) // Another root

        // When
        val rootCategories = categoryDao.getRootCategories().first()

        // Then
        assertEquals(2, rootCategories.size)
        assertTrue(rootCategories.all { it.parentId == null })
        assertTrue(rootCategories.any { it.name == "Food" })
        assertTrue(rootCategories.any { it.name == "Transport" })
    }

    @Test
    fun getRootCategoriesSnapshot_returnsSnapshot() = runTest {
        // Given
        categoryDao.insert(createTestCategory(name = "Food"))
        categoryDao.insert(createTestCategory(name = "Transport"))

        // When
        val rootCategories = categoryDao.getRootCategoriesSnapshot()

        // Then
        assertEquals(2, rootCategories.size)
        assertTrue(rootCategories.all { it.parentId == null })
    }

    @Test
    fun getSubcategories_returnsOnlyChildrenOfParent() = runTest {
        // Given
        val foodId = categoryDao.insert(createTestCategory(name = "Food"))
        val transportId = categoryDao.insert(createTestCategory(name = "Transport"))
        categoryDao.insert(createTestCategory(name = "Restaurants", parentId = foodId))
        categoryDao.insert(createTestCategory(name = "Groceries", parentId = foodId))
        categoryDao.insert(createTestCategory(name = "Taxi", parentId = transportId))

        // When
        val foodSubcategories = categoryDao.getSubcategories(foodId).first()
        val transportSubcategories = categoryDao.getSubcategories(transportId).first()

        // Then
        assertEquals(2, foodSubcategories.size)
        assertTrue(foodSubcategories.all { it.parentId == foodId })
        assertTrue(foodSubcategories.any { it.name == "Restaurants" })
        assertTrue(foodSubcategories.any { it.name == "Groceries" })

        assertEquals(1, transportSubcategories.size)
        assertEquals(transportId, transportSubcategories[0].parentId)
        assertEquals("Taxi", transportSubcategories[0].name)
    }

    @Test
    fun getSubcategoriesSnapshot_returnsSnapshot() = runTest {
        // Given
        val parentId = categoryDao.insert(createTestCategory(name = "Food"))
        categoryDao.insert(createTestCategory(name = "Restaurants", parentId = parentId))
        categoryDao.insert(createTestCategory(name = "Groceries", parentId = parentId))

        // When
        val subcategories = categoryDao.getSubcategoriesSnapshot(parentId)

        // Then
        assertEquals(2, subcategories.size)
        assertTrue(subcategories.all { it.parentId == parentId })
    }

    @Test
    fun getSubcategories_parentWithNoChildren_returnsEmpty() = runTest {
        // Given
        val parentId = categoryDao.insert(createTestCategory(name = "Food"))

        // When
        val subcategories = categoryDao.getSubcategories(parentId).first()

        // Then
        assertTrue(subcategories.isEmpty())
    }

    @Test
    fun getSubcategories_sortedCorrectly() = runTest {
        // Given
        val parentId = categoryDao.insert(createTestCategory(name = "Food"))
        categoryDao.insert(createTestCategory(name = "Zulu Sub", parentId = parentId, sortOrder = 2))
        categoryDao.insert(createTestCategory(name = "Alpha Sub", parentId = parentId, sortOrder = 1))
        categoryDao.insert(createTestCategory(name = "Bravo Sub", parentId = parentId, sortOrder = 1))

        // When
        val subcategories = categoryDao.getSubcategories(parentId).first()

        // Then
        assertEquals(3, subcategories.size)
        assertEquals("Alpha Sub", subcategories[0].name)
        assertEquals("Bravo Sub", subcategories[1].name)
        assertEquals("Zulu Sub", subcategories[2].name)
    }

    // ==================== Search Tests ====================

    @Test
    fun searchByName_partialMatch_returnsMatches() = runTest {
        // Given
        categoryDao.insertAll(
            listOf(
                createTestCategory(name = "Food & Beverages"),
                createTestCategory(name = "Fast Food"),
                createTestCategory(name = "Transport")
            )
        )

        // When
        val results = categoryDao.searchByName("food").first()

        // Then
        assertEquals(2, results.size)
        assertTrue(results.any { it.name == "Food & Beverages" })
        assertTrue(results.any { it.name == "Fast Food" })
    }

    @Test
    fun searchByName_caseInsensitive() = runTest {
        // Given
        categoryDao.insert(createTestCategory(name = "Shopping"))

        // When
        val results = categoryDao.searchByName("SHOPPING").first()

        // Then
        assertEquals(1, results.size)
        assertEquals("Shopping", results[0].name)
    }

    @Test
    fun searchByName_noMatches_returnsEmpty() = runTest {
        // Given
        categoryDao.insert(createTestCategory(name = "Food"))

        // When
        val results = categoryDao.searchByName("xyz").first()

        // Then
        assertTrue(results.isEmpty())
    }

    @Test
    fun searchByName_emptyQuery_returnsAll() = runTest {
        // Given
        categoryDao.insertAll(
            listOf(
                createTestCategory(name = "Food"),
                createTestCategory(name = "Transport")
            )
        )

        // When
        val results = categoryDao.searchByName("").first()

        // Then
        assertEquals(2, results.size)
    }

    @Test
    fun searchByNameSnapshot_returnsSnapshot() = runTest {
        // Given
        categoryDao.insert(createTestCategory(name = "Shopping"))

        // When
        val results = categoryDao.searchByNameSnapshot("shop")

        // Then
        assertEquals(1, results.size)
    }

    // ==================== System vs Custom Category Tests ====================

    @Test
    fun getSystemCategories_returnsOnlySystemCategories() = runTest {
        // Given
        categoryDao.insertAll(
            listOf(
                createTestCategory(name = "System Food", isSystemCategory = true),
                createTestCategory(name = "System Transport", isSystemCategory = true),
                createTestCategory(name = "Custom Shopping", isSystemCategory = false)
            )
        )

        // When
        val systemCategories = categoryDao.getSystemCategories().first()

        // Then
        assertEquals(2, systemCategories.size)
        assertTrue(systemCategories.all { it.isSystemCategory })
        assertTrue(systemCategories.any { it.name == "System Food" })
        assertTrue(systemCategories.any { it.name == "System Transport" })
    }

    @Test
    fun getSystemCategoriesSnapshot_returnsSnapshot() = runTest {
        // Given
        categoryDao.insert(createTestCategory(name = "System Food", isSystemCategory = true))

        // When
        val systemCategories = categoryDao.getSystemCategoriesSnapshot()

        // Then
        assertEquals(1, systemCategories.size)
        assertTrue(systemCategories[0].isSystemCategory)
    }

    @Test
    fun getCustomCategories_returnsOnlyCustomCategories() = runTest {
        // Given
        categoryDao.insertAll(
            listOf(
                createTestCategory(name = "System Food", isSystemCategory = true),
                createTestCategory(name = "Custom Transport", isSystemCategory = false),
                createTestCategory(name = "Custom Shopping", isSystemCategory = false)
            )
        )

        // When
        val customCategories = categoryDao.getCustomCategories().first()

        // Then
        assertEquals(2, customCategories.size)
        assertTrue(customCategories.all { !it.isSystemCategory })
        assertTrue(customCategories.any { it.name == "Custom Transport" })
        assertTrue(customCategories.any { it.name == "Custom Shopping" })
    }

    @Test
    fun getCustomCategoriesSnapshot_returnsSnapshot() = runTest {
        // Given
        categoryDao.insert(createTestCategory(name = "Custom Food", isSystemCategory = false))

        // When
        val customCategories = categoryDao.getCustomCategoriesSnapshot()

        // Then
        assertEquals(1, customCategories.size)
        assertFalse(customCategories[0].isSystemCategory)
    }

    // ==================== Existence and Count Tests ====================

    @Test
    fun exists_existingCategory_returnsTrue() = runTest {
        // Given
        val category = createTestCategory(name = "Food")
        val rowId = categoryDao.insert(category)

        // When
        val exists = categoryDao.exists(rowId)

        // Then
        assertTrue(exists)
    }

    @Test
    fun exists_nonExistentCategory_returnsFalse() = runTest {
        // When
        val exists = categoryDao.exists(999)

        // Then
        assertFalse(exists)
    }

    @Test
    fun existsByName_existingName_returnsTrue() = runTest {
        // Given
        categoryDao.insert(createTestCategory(name = "Food"))

        // When
        val exists = categoryDao.existsByName("Food")

        // Then
        assertTrue(exists)
    }

    @Test
    fun existsByName_caseInsensitive() = runTest {
        // Given
        categoryDao.insert(createTestCategory(name = "Shopping"))

        // When
        val exists = categoryDao.existsByName("SHOPPING")

        // Then
        assertTrue(exists)
    }

    @Test
    fun existsByName_nonExistentName_returnsFalse() = runTest {
        // When
        val exists = categoryDao.existsByName("NonExistent")

        // Then
        assertFalse(exists)
    }

    @Test
    fun getCategoryCount_returnsCorrectCount() = runTest {
        // Given
        categoryDao.insertAll(
            listOf(
                createTestCategory(name = "Food"),
                createTestCategory(name = "Transport"),
                createTestCategory(name = "Shopping")
            )
        )

        // When
        val count = categoryDao.getCategoryCount()

        // Then
        assertEquals(3, count)
    }

    @Test
    fun getCategoryCount_emptyDatabase_returnsZero() = runTest {
        // When
        val count = categoryDao.getCategoryCount()

        // Then
        assertEquals(0, count)
    }

    @Test
    fun getSubcategoryCount_returnsCorrectCount() = runTest {
        // Given
        val parentId = categoryDao.insert(createTestCategory(name = "Food"))
        categoryDao.insert(createTestCategory(name = "Restaurants", parentId = parentId))
        categoryDao.insert(createTestCategory(name = "Groceries", parentId = parentId))
        categoryDao.insert(createTestCategory(name = "Fast Food", parentId = parentId))

        // When
        val count = categoryDao.getSubcategoryCount(parentId)

        // Then
        assertEquals(3, count)
    }

    @Test
    fun getSubcategoryCount_parentWithNoChildren_returnsZero() = runTest {
        // Given
        val parentId = categoryDao.insert(createTestCategory(name = "Food"))

        // When
        val count = categoryDao.getSubcategoryCount(parentId)

        // Then
        assertEquals(0, count)
    }

    // ==================== Sort Order Tests ====================

    @Test
    fun getMaxSortOrder_returnsHighestValue() = runTest {
        // Given
        categoryDao.insertAll(
            listOf(
                createTestCategory(name = "Cat1", sortOrder = 1),
                createTestCategory(name = "Cat2", sortOrder = 5),
                createTestCategory(name = "Cat3", sortOrder = 3)
            )
        )

        // When
        val maxSortOrder = categoryDao.getMaxSortOrder()

        // Then
        assertEquals(5, maxSortOrder)
    }

    @Test
    fun getMaxSortOrder_emptyDatabase_returnsZero() = runTest {
        // When
        val maxSortOrder = categoryDao.getMaxSortOrder()

        // Then
        assertEquals(0, maxSortOrder)
    }

    @Test
    fun getMaxSortOrderForParent_returnsHighestValueForParent() = runTest {
        // Given
        val parentId = categoryDao.insert(createTestCategory(name = "Food"))
        categoryDao.insert(createTestCategory(name = "Sub1", parentId = parentId, sortOrder = 2))
        categoryDao.insert(createTestCategory(name = "Sub2", parentId = parentId, sortOrder = 7))
        categoryDao.insert(createTestCategory(name = "Sub3", parentId = parentId, sortOrder = 4))

        // When
        val maxSortOrder = categoryDao.getMaxSortOrderForParent(parentId)

        // Then
        assertEquals(7, maxSortOrder)
    }

    @Test
    fun getMaxSortOrderForParent_parentWithNoChildren_returnsZero() = runTest {
        // Given
        val parentId = categoryDao.insert(createTestCategory(name = "Food"))

        // When
        val maxSortOrder = categoryDao.getMaxSortOrderForParent(parentId)

        // Then
        assertEquals(0, maxSortOrder)
    }

    // ==================== Flow Reactivity Tests ====================

    @Test
    fun getAllCategoriesFlow_reactsToInsert() = runTest {
        // Given - Flow subscriber
        val flow = categoryDao.getAllCategories()

        // Initial empty state
        assertEquals(0, flow.first().size)

        // When - Insert category
        categoryDao.insert(createTestCategory(name = "Food"))

        // Then - Flow should emit updated list
        val updated = flow.first()
        assertEquals(1, updated.size)
        assertEquals("Food", updated[0].name)
    }

    @Test
    fun getCategoryByIdFlow_reactsToUpdate() = runTest {
        // Given
        val category = createTestCategory(name = "Original")
        val rowId = categoryDao.insert(category)
        val flow = categoryDao.getCategoryByIdFlow(rowId)

        // Verify initial state
        assertEquals("Original", flow.first()?.name)

        // When - Update category
        categoryDao.update(category.copy(id = rowId, name = "Updated"))

        // Then - Flow should emit updated category
        val updated = flow.first()
        assertEquals("Updated", updated?.name)
    }

    @Test
    fun getRootCategoriesFlow_reactsToDelete() = runTest {
        // Given
        val id1 = categoryDao.insert(createTestCategory(name = "Food"))
        val id2 = categoryDao.insert(createTestCategory(name = "Transport"))
        val flow = categoryDao.getRootCategories()

        // Verify initial state
        assertEquals(2, flow.first().size)

        // When - Delete one category
        categoryDao.deleteById(id1)

        // Then - Flow should emit updated list
        val updated = flow.first()
        assertEquals(1, updated.size)
        assertEquals("Transport", updated[0].name)
    }

    @Test
    fun getSubcategoriesFlow_reactsToInsert() = runTest {
        // Given
        val parentId = categoryDao.insert(createTestCategory(name = "Food"))
        val flow = categoryDao.getSubcategories(parentId)

        // Initial empty state
        assertEquals(0, flow.first().size)

        // When - Add subcategory
        categoryDao.insert(createTestCategory(name = "Restaurants", parentId = parentId))

        // Then - Flow should emit updated list
        val updated = flow.first()
        assertEquals(1, updated.size)
        assertEquals("Restaurants", updated[0].name)
    }

    // ==================== Edge Cases ====================

    @Test
    fun insert_withSpecialCharactersInName() = runTest {
        // Given
        val category = createTestCategory(name = "Food & Beverages™️ (新しい)")

        // When
        val rowId = categoryDao.insert(category)

        // Then
        val loaded = categoryDao.getCategoryById(rowId)
        assertEquals("Food & Beverages™️ (新しい)", loaded?.name)
    }

    @Test
    fun insert_withVeryLongKeywords() = runTest {
        // Given
        val longKeywords = (1..100).joinToString(",") { "keyword$it" }
        val category = createTestCategory(keywords = longKeywords)

        // When
        val rowId = categoryDao.insert(category)

        // Then
        val loaded = categoryDao.getCategoryById(rowId)
        assertEquals(longKeywords, loaded?.keywords)
    }

    @Test
    fun insert_withEmptyKeywords() = runTest {
        // Given
        val category = createTestCategory(keywords = "")

        // When
        val rowId = categoryDao.insert(category)

        // Then
        val loaded = categoryDao.getCategoryById(rowId)
        assertEquals("", loaded?.keywords)
    }

    @Test
    fun insert_withMaxTimestamp() = runTest {
        // Given
        val category = createTestCategory(
            createdAt = Long.MAX_VALUE,
            updatedAt = Long.MAX_VALUE
        )

        // When
        val rowId = categoryDao.insert(category)

        // Then
        val loaded = categoryDao.getCategoryById(rowId)
        assertEquals(Long.MAX_VALUE, loaded?.createdAt)
        assertEquals(Long.MAX_VALUE, loaded?.updatedAt)
    }

    @Test
    fun insert_withMinTimestamp() = runTest {
        // Given
        val category = createTestCategory(
            createdAt = 0L,
            updatedAt = 0L
        )

        // When
        val rowId = categoryDao.insert(category)

        // Then
        val loaded = categoryDao.getCategoryById(rowId)
        assertEquals(0L, loaded?.createdAt)
        assertEquals(0L, loaded?.updatedAt)
    }

    @Test
    fun insert_withNegativeSortOrder() = runTest {
        // Given
        val category = createTestCategory(sortOrder = -1)

        // When
        val rowId = categoryDao.insert(category)

        // Then
        val loaded = categoryDao.getCategoryById(rowId)
        assertEquals(-1, loaded?.sortOrder)
    }

    @Test
    fun searchByName_withSpecialCharacters() = runTest {
        // Given
        categoryDao.insert(createTestCategory(name = "Food & Beverages"))

        // When
        val results = categoryDao.searchByName("&").first()

        // Then
        assertEquals(1, results.size)
        assertEquals("Food & Beverages", results[0].name)
    }

    @Test
    fun cascadeDelete_complexHierarchy() = runTest {
        // Given - Complex hierarchy
        val root = categoryDao.insert(createTestCategory(name = "Root"))
        val child1 = categoryDao.insert(createTestCategory(name = "Child1", parentId = root))
        val child2 = categoryDao.insert(createTestCategory(name = "Child2", parentId = root))
        val grandchild1 = categoryDao.insert(createTestCategory(name = "Grandchild1", parentId = child1))
        val grandchild2 = categoryDao.insert(createTestCategory(name = "Grandchild2", parentId = child2))

        // Verify setup
        assertEquals(5, categoryDao.getCategoryCount())

        // When - Delete root
        categoryDao.deleteById(root)

        // Then - All descendants should be deleted
        assertEquals(0, categoryDao.getCategoryCount())
    }

    @Test
    fun insertAll_withLargeBatch() = runTest {
        // Given
        val largeBatch = (1..1000).map { i ->
            createTestCategory(name = "Category $i", sortOrder = i)
        }

        // When
        val rowIds = categoryDao.insertAll(largeBatch)

        // Then
        assertEquals(1000, rowIds.size)
        assertEquals(1000, categoryDao.getCategoryCount())
    }

    @Test
    fun operations_maintainDataIntegrity() = runTest {
        // Given - Insert categories
        val foodId = categoryDao.insert(createTestCategory(name = "Food", sortOrder = 1))
        val restaurantsId = categoryDao.insert(createTestCategory(name = "Restaurants", parentId = foodId, sortOrder = 1))

        // When - Multiple operations
        categoryDao.update(createTestCategory(id = foodId, name = "Food & Beverages", sortOrder = 2))
        val groceriesId = categoryDao.insert(createTestCategory(name = "Groceries", parentId = foodId, sortOrder = 2))

        // Then - Verify data integrity
        val food = categoryDao.getCategoryById(foodId)
        assertEquals("Food & Beverages", food?.name)
        assertEquals(2, food?.sortOrder)

        val subcategories = categoryDao.getSubcategoriesSnapshot(foodId)
        assertEquals(2, subcategories.size)
        assertTrue(subcategories.any { it.name == "Restaurants" })
        assertTrue(subcategories.any { it.name == "Groceries" })
    }
}
